local function firstMenu()
term.clear()
gpu.setBackground(0xCCCCCC)
local w,h = gpu.getResolution()
gpu.fill(1,1,w,h," ")
gpu.setBackground(0x424242)
gpu.setForeground(0xFFFFFF)
gpu.fill(1,1,w,1," ")
gpu.set(1,1,"Select what to boot:")
gpu.setBackground(0xCCCCCC)
gpu.setForeground(0x000000)
gpu.fill(1,2,w,2," ")
gpu.set(1,2,"System")
gpu.setBackground(0x424242)
gpu.setForeground(0xFFFFFF)
gpu.fill(1,3,w,3," ")
gpu.set(1,3,"Recovery")
end
firstMenu()
os.sleep(1)
